### ISSUE TITLE
about frame_num

### ISSUE THREAD

**Issue by bugcat9** [VividLe/BackTAL#3]
大佬想问一下，在 dataset.py 文件中`__getitem__`中返回的`frame_num`是什么含义，似乎不是视频的片段数。🤣

**Comment by VividLe** [comment]
The item frame_num indicates the number of feature vectors in the video.

For example, given a video feature with shape [2048, 1000], 2048 indicates feature dimension and the corresponding frame_num is 1000.

**Comment by bugcat9** [comment]
ok,thank you.
