### ISSUE TITLE
about background click

### ISSUE THREAD

**Issue by L-hiker** [VividLe/BackTAL#7]
Thank you for your excellent work！But I have some questions about the use of background click information. In the code, except for score separation module and affinity module, I can't find the use of click_label anywhere else. So I want to know how to implement the experiment that includes background click but removes these two modules in the ablation experiment. There must be something I missed here. Can you give me some help? Thank you very much.

**Comment by VividLe** [comment]
In addition to these two modules, we conduct click-level classification on annotated background frames. For ablation experiments, please remove these two modules.

**Comment by L-hiker** [comment]
Thank you for your reply. The click-level classification should be the Lfram in the paper, but I'm not sure in the code. Is it relate to loss_ click_ Base?
